apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    app: {{ .Release.Name }}-backend-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port}}
      targetPort: {{ .Values.backend.port}}
  selector:
    app: {{ .Release.Name }}-backend-pod
