apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Release.Name }}-frontend-deployment
  labels:
    app: {{ .Release.Name }}-frontend-deployment

spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend-pod

  template:
    metadata:
      name: {{ .Release.Name }}-frontend-pod
      labels:
        app: {{ .Release.Name }}-frontend-pod

    spec:
      containers:
        - name: {{ .Release.Name }}-frontend-container
          image: {{ .Values.frontend.image }}: {{ .Values.frontend.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: "/etc/nginx/nginx.conf"
              subPath: "nginx.conf"
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-configmap

